### ISSUE TITLE
Do you plan to put this on MELPA?

### ISSUE THREAD

**Issue by minad** [mohkale/consult-eglot#1]

**Comment by mohkale** [comment]
Yep. See [melpa#7684](https://github.com/melpa/melpa/pull/7684) :smile:.

**Comment by minad** [comment]
Regarding you other `consult-*` packages, I assume you will also publish them via MELPA? I linked your packages here: https://github.com/minad/consult/#recommended-packages

**Comment by mohkale** [comment]
@minad 

Yes. That's part of the plan :smile:.

**Comment by minad** [comment]
Cool. I wonder a bit about of the necessity of `consult-bibtex`. Isn't `bibtex-actions` more sophisticated and flexible? I also like that it is completion system agnostic. There are so many bibliography-related packages, I lost track.

* consult-bibtex
* bibtex-actions
* bibtex-completion, ivy-bibtex, helm-bibtex
* org-ref
* org-ref-cite
* org-cite mechanism in org
* biblio
* ...

Of course there may be some genuine advantage of each of these packages, but I would prefer it more if there is some consolidation.

**Comment by mohkale** [comment]
@minad 

I'm inclined to agree but I'm not using bibtex-actions. Mostly because it seems very large and very feature-full but all I really needed was a wrapper around bibtex-completion which I was already using for a while. That's why I wrote `consult-bibtex`. I moved it into it's own repo mostly because someone asked me to (see [mohkale/emacs#1](https://github.com/mohkale/emacs/issues/1)). There's probably not much reason for consult-bibtex to use consult, although I like and do make use of narrowing quite a bit.

As for everythig else you've mentioned, here's how I currently seee things.

`bibtex-actions`, `consult-bibtex`, `ivy-bibtex` and `helm-bibtex` all seem to be frontends (as in UI layers) for `bibtex-completion`. `bibtex-completion` is a package that lets you reference and act on bibliography entries from multiple bibtex files. You can see most of the exposed commands in `consult-bibtex-embark` (which're just wrappers around the non-interactive `bibtex-completion` functions, but for example you can associate bibtex entries with a PDFs directory and then open corresponding PDFs from emacs).

`org-ref` gives you some really cool org-mode extensions for dealing with bibliographies and references (the autoref link type is really useful and minibuffer link previews is helpful). It also includes `doi-utils` which lets you quickly fetch PDFs or insert bibtex entries from DOI codes. `org-cite` is a recent addition to org-mode to support bibliographies (it's too new for me atm so I haven't looked into it very much). `org-ref-cite` is an `org-ref` extension for compatibility with `org-cite` (that's actually really cool, I'll look into it soon). I've never heard of biblio and I believe `parsebib` is the library `bibtex-completion` uses to parse bibtex files into lisp data structures.

Honestly I agree there's quite a lot of fragmentation, although everything I use (bibtex-completion + org-ref + consult-bibtex) are suitably different enough for me to be happy with the slight overlapping functionality. That said there should probably be a unifying package bundling them all together. Just like I believe you mentioned eventually there'll be one for consult+embark+marginalia+selectrum/vertico etc.

**Comment by minad** [comment]
Thanks for your answer. My opinion regarding `bibtex-completion` is that instead of functions, it should use commands directly with an `interactive` specification to select entries via `completing-read`. This was originally proposed in a PR to `bibtex-completion`, but didn't make it in. I've heard that `bibtex-actions` is slowly abandoning `bibtex-completion` and moving over to `parsebib` only. Regarding `org-ref` there seems to be also some movement to make it more decoupled from helm and ivy and integrate it with the new `org-cite` extension and abandoning `org-ref-cite` on the way. We will see which solution turns out to attract most users.

> That said there should probably be a unifying package bundling them all together. Just like I believe you mentioned eventually there'll be one for consult+embark+marginalia+selectrum/vertico etc.

No, I never believed such a unifying bundling package should exist. There was some talking on reddit and on the issue trackers that selectrum etc is too hard to setup and such a bundle should exist. I was never convinced of that. I think it is much better to have small modular components and user put them together in their configuration. Users who want something prebundled can use distributions like Doom, Spacemacs or build something from some existing configurations. I also don't think the packages are hard to setup - not harder than other commonly used Emacs packages. See https://github.com/minad/vertico/#complementary-packages for my recommended way to use the packages, which should even be beginner friendly. At least if there is some basic familiarity with how Emacs works.
