### ISSUE TITLE
code actions?

### ISSUE THREAD

**Issue by unhammer** [mohkale/consult-eglot#11]
Could this also show code actions available in the file?

**Comment by mohkale** [comment]
This should already be supported with eglot, no need to add another command to consult-eglot. Have you tried `M-x eglot-code-actions`?

**Comment by unhammer** [comment]
Yes, that seems to only show code actions at point, I'm interested in an overview for the file. (But maybe it'd be better to have such things in the fringe anyway)

**Comment by mohkale** [comment]
> Yes, that seems to only show code actions at point, I'm interested in an overview for the file

I'm not quite sure how to accomplish this. The language server API doesn't support querying code actions for the entire file (to the best of my knowledge). We could perhaps query the actions for every line or character in a file but it would be a lot of traffic for an action that would have to be better supported upstream of this plugin. If you could point out an API request that can facilitate this I'd be happy to add support here (although I'd imagine that would be better served in eglot itself instead of this plugin).

**Comment by unhammer** [comment]
Fair enough; I thought this was something lsp-mode already did, but perhaps those were not code actions but "warnings" (e.g. from hlint)

**Comment by mohkale** [comment]
> but perhaps those were not code actions but "warnings"

Warnings are supported and eglot integrates them into flymake so their rendered in the window. I'm closing this ticket for now, but you can reopen if anything changes to make this more feasible.
