### ISSUE TITLE
Using built-in Eglot in Emacs 30.0.50?

### ISSUE THREAD

**Issue by johnhamelink** [mohkale/consult-eglot#15]
Hi there,

When I install consult-eglot with Straight on Emacs master branch, Straight clones and builds Eglot - but Emacs 30.0.50 comes with a newer version of Eglot installed already. How might I force consult-eglot to use the version of Eglot that's already installed?

**Comment by mohkale** [comment]
@johnhamelink 

consult-eglot will use whatever eglot version you have loaded. This isn't configured by us. I'd recommend asking on the straight repo to explain why. Because I'm using eglot through git and emacs 30, I imagine you must not be loading or declaring them in the correct order. If you load consult-eglot it will load eglot. If you install eglot from git after this, you will still have the original eglot loaded. Please confirm you're deferring consult-eglot from being loaded or installing eglot from git before installing consult-eglot.

I'm going to go ahead and close this issue, feel free to continue commenting or asking questions.
