### ISSUE TITLE
consult-eglot-symbols preview is jittery during typing

### ISSUE THREAD

**Issue by ville-h** [mohkale/consult-eglot#20]
`consult-eglot-symbols` preview is jittery during typing. When typing characters the preview seems to always flash some "default" buffer for a very brief time (<0.1s) before displaying the correct buffer. Even if the newly typed character previews the exact same symbol and buffer that was already being displayed. Could this be improved so there wasn't this behaviour?

I don't know if this is due to consult it self or consult-eglot.

**Comment by mohkale** [comment]
I think this is just how file previews work. consult will make a temporary buffer, copy in the contents of the file being previewed and then go to the point of the preview. If the jittery buffers name is `Preview:*` then that's it. The jitteryness is opening and syntax highlighting the buffer. If your emacs instance is fast to do all of that it isn't so noticeable. I'd suggest using tree-sitter given most of the slowness in rendering is font-lock and tree-sitter is super fast.

Closing since I don't think there's much we can do here. If you observe this in consult-eglot but not with consult-ripgrep or variants to the same files than there might be more to look into here.
